# Whole guidline can be found here: https://www.netlifycms.org/docs/configuration-options/

backend:
  name: git-gateway #When testing you can use test-repo else git-gateway
  branch: master # Branch to update (optional; defaults to master)

site_url: https://vught.netlify.com
display_url: https://vught.netlify.com

media_folder: "static/uploads" # Media files will be stored in the repo under static/uploads
public_folder: "/uploads" # The src attribute for uploaded media will begin with /uploads

collections:
  - label: "Logo" #  label for the collection in the editor UI; defaults to the value of name
    name: "logo" # (required): unique identifier for the collection, used as the key when referenced in other contexts
    folder: "content/Logo" # Location where the file will be saved
    slug: "{{slug}}"
    create: true # allows users to create new items in the collection
    description: "Ensure that there is only one item in this category." # A description that will displayed below the  in the CMs
    fields: # widget: defines editor UI and inputs and file field data types; for more detail go to : https://www.netlifycms.org/docs/widgets/
      - {name: "title", label: "Title", widget: "string"}
      - {name: "logo", label: "Logo", widget: "image"}
  - label: "Menu items" #  label for the collection in the editor UI; defaults to the value of name
    name: "menu" # (required): unique identifier for the collection, used as the key when referenced in other contexts
    folder: "content/Menu" # Location where the file will be saved
    slug: "{{slug}}"
    create: true
    description: "Create menu items that will be added to the navigation. Max (7)" # A description that will displayed below the  in the CMs
    fields: # widget: defines editor UI and inputs and file field data types; for more detail go to : https://www.netlifycms.org/docs/widgets/
      - {label: "Menu item", name: "menu-item", widget: "string"}
  - label: "Jumbotron" #  label for the collection in the editor UI; defaults to the value of name
    name: "jumbotron" # (required): unique identifier for the collection, used as the key when referenced in other contexts
    folder: "content/Jumbotron" # Location where the file will be saved
    slug: "{{slug}}"
    create: true
    description: "Create items to be highlighted. Max (3)" # A description that will displayed below the  in the CMs
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
  - label: "Post - publication"
    name: "post-publicatie"
    folder: "content/Post/Publication"
    slug: "{{slug}}"
    create: true
    description: "Create publication post"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", format: "DD-MM-YYYY", widget: "date"}
      - {label: "Reason", name: "reason", default: "Publicatie", widget: "hidden"} # Will not be displayed in the CMS UI
      - {label: "Body", name: "body", widget: "markdown"}


